### ISSUE TITLE
How to trigger using webcron?

### ISSUE THREAD

**Issue by joephein** [rullzer/previewgenerator#10]
I am on shared hosting. Is there a way to trigger this using webcron? How does this app actually work? Will it generate previews for new images only? What are the resolutions of the generated previews? Only the default 2048x2048?

**Comment by rullzer** [comment]
This app is not ment to be triggered from webcron. As it can take a long time for previews to be generated. 

It genertes a (pre set) number of previews. But there are plans to make this somewhat configurable.
