### ISSUE TITLE
previewgenerator running in maintenance mode and database integrity?

### ISSUE THREAD

**Issue by Beres-Berlin** [rullzer/previewgenerator#100]
Hi!

greatly enjoying the previewgenerator app! I have one question though:

I have written a shell script for automatic backups (data, config, themes directories and mysql-dump as a tar.gzip to an NAS or external hdd via crontab). The backup starts in maintenance mode (as recommended in the nextcloud 12 documentation). But I'm not sure how to proceed with the previewgenerator generating previews in the background. I have tested and enabled maintenance mode while previewgenerator is running => the previewgenerator keeps generating files. As far as I understand, the database will not "like this" (please excuse my language here, very little LAMP-experience...) as new files are being generated, correct?

So my idea for a solution would be to test if the previewgenerator is running and only start the backup-process if it is not running. Correct?

**Comment by rullzer** [comment]
Ah yes since the process is running that is not yet in maintenance mode.

So yes, please check if it is running.

ANd I'll see if i can check that every iteration as well or so and just stop generating then.

**Comment by Beres-Berlin** [comment]
...to clarify: started previewgenerator (via cronjob), enabled maintenance mode, tried to create mysql-dump => "...could not create *.bak. missing permissions"

**Comment by Beres-Berlin** [comment]
found a solution:
...
SCRIPT=$(ps aux | grep "pre-generate" | grep -v "grep" | wc -l)
...
if [ $SCRIPT -ge 1 ]

 then

  echo 'Prozess preview:pre-generate läuft. Wartungsmodus nicht aktiviert, kein Backup erstellt.'

**Comment by rullzer** [comment]
Ah yes this was on my todo list to suggest. :)

Glad it worked ou!
