### ISSUE TITLE
Specify password for external shares

### ISSUE THREAD

**Issue by IteDas** [rullzer/previewgenerator#103]
It would be nice if the preview generator would not crash when coming accross an external share it does not have a password for or use the user's saved / supplied password.

**Comment by anduz** [comment]
Hello,
when running
sudo -u www-data ./occ preview:pre-generate
after
univention-app shell nextcloud
it doesn't seem to do anything, no process in ps -aux.
System is UCS with NC12
using 
- AD integration with Windows SBS 2008
- external storage with session credentials

I think I need a way to give credentials for preview:pre-generate

**Comment by rullzer** [comment]
Mmm yes we should probably handle fetching files a bit better. However providing credentials is not something feasible as you'll have to enter them in cron. And this is not secure to have just lying around in your crontab.

**Comment by fermulator** [comment]
Any suggestions for workaround?

**Comment by fermulator** [comment]
@rullzer , any feedback/guidance into design of solution? (I'm interested to help but would like a primer before starting)

**Comment by ChristophWurst** [comment]
I think it's best if we just catch the `StorageNotAvailableException` and carry on.
