### ISSUE TITLE
Question - Is it ok if a preview job is running while another starts?

### ISSUE THREAD

**Issue by Iolaum** [rullzer/previewgenerator#110]
Hello,

I am [looking on how to configure](https://github.com/nextcloud/nextcloudpi/issues/470) the Preview Generator app for my NextCloudPi instance. Because the raspberry pi (that's mostly used for it) is slow when Generating Previews it could well happen that once a user uploads a new batch of photos the preview generation will take long enough that another preview generation may get started with cron.

Will that create problems conflicts? I am asking so we know how further away we should schedule the cron jobs once we automatically enable Preview Generator on the project to not create problems for our users. Or what guidelines we should give to our users when they will be deciding how often to schedule the process. The 15min suggested on the projects README sounds bad for small NC instances running on low power arm boards if a new preview generation job can create conflicts with an existing running preview generation job.

**Comment by rullzer** [comment]
This will work just fine. The app checks if there is already a running process.
