### ISSUE TITLE
Why are some previews JPG, some PNG, and some GIF?

### ISSUE THREAD

**Issue by schniepp** [rullzer/previewgenerator#111]
I currently have about 2 million preview files in my Nextcloud instance (using default settings, so about 20 previews for each image file). About 1.3M are PNGs, 0.6M are JPGs, and about 4K are GIFs. Total size of just the previews is about 182GB. Why is PNG used in most cases? Especially for photos, JPG offers a much better compression ratio, so using PNG will not only bloat file size on disk but also increase download bandwidth when previews are watched, which will affect speed. 

I have maintained the data+database for a few years, which means I have upgraded across several ownCloud, Nextcloud (and php) versions; I have also upgraded and fixed hardware along the way. To this point all transitions were quite smooth. However, it is possible that I have not had the exact same php extensions/packages installed at different times. Could this be the reason why I got different formats for the previews? Right now I am on NC13.0.0 and php7.1 (want to switch to php7.2 soon).

**Comment by schniepp** [comment]
OK, I am just realizing this now: would this really be a _gallery_ issue and not a _previewgenerator_ issue? Or Nextcloud core?

In other words, does the _previewgenerator_ app simply trigger the generation of previews using the same mechanism that gallery/Nextcloud would use if a particular folder/image was simply visited?

**Comment by Darkvater** [comment]
Yes. The preview generator just hooks up into nextcloud to request a preview. Nothing more.

**Comment by rullzer** [comment]
Yes we just hook into the server preview stuff.

Having said that. It used to be the case we just saved everything as preview (some legacy leftover). This is fixed in NC13. So starting NC13 previews are actually generated with the correct suffix.

**Comment by GAS85** [comment]
Still have similar issue in NC 18.0.4:
```
# find preview -type f -name "*.png" | wc -l
15546
# find preview -type f -name "*.gif" | wc -l
1544
# find preview -type f -name "*.jpg" | wc -l
395965
```

And as per here it could be a problem: https://help.nextcloud.com/t/large-thumbnails-size-in-the-files-app/80525/
