### ISSUE TITLE
stupid noobie question(s)

### ISSUE THREAD

**Issue by rwat1** [rullzer/previewgenerator#112]
Dear all,

I am new to NextCloud, I had a few questions about the Preview Generator app.

1. Can this app generate previews for the NextCloud iOS app on iPhone? Or does it only generate thumbnails for WebGUI only (Gallery app?)... (i typically use NC iOS app on iPhone to look at thumbnails)

2.  Can this app generate previews for ALL media/photos in NC, or does it generate thumbnails for only newly uploaded photos? (e.g. I want to generate previews for older photos already uploaded)
 
3. Does this preview generator get triggered when new photos are uploaded via WebGUI only? How about other clients? (e.g. I typically use the NC Windows Desktop Sync Client to upload photos/media, never WebGUI)
 
4. Can this preview generator detect if a photo already has thumbnails generated previously, or will it Overwrite the old thumbnails, or will it Duplicate the thumbnails? ( i don't want too many duplicates, eats up storage space)

5. Can this preview generator generate thumbnails for Videos? On my iOS app, the Videos thumbnails cannot generate automatically, they look like grey squares.

6. Can I see how much space the previews are taking up? Can I delete all previews?

Thank you so much, I appreciate everyone's help.

**Comment by schniepp** [comment]
My understanding of this is not very deep yet, but I will try to answer.

1. I am using the Android app, and for this the pre-generated previews speed up quite a bit.
2. Depends on which one you use. `preview:generate-all` will generate previews for all files, `preview:pre-generate`  only for newly created/added pictures (but not on external shares).
3. I am guessing it will be independent of the upload mechanism
4. If the preview is already generated, it will not be generated again. If you interrupt the job and restart, it will go very quickly for folders that had previously been done.
5. I believe so. In my case, it also creates thumbnails for DOCX, PPTX, PDF, etc.
6. They are in a preview folder inside of your data folder. It should look something like `appdata_oc??????????/preview`. In my case, the file size is very, very large. About 20 previews are generated for every picture, and in my case many of them are PNG, which is not a very efficient way to compress images (especially stuff like photos).

**Comment by rullzer** [comment]
let me complete the response by @schniepp 

1. I don't know if IOS uses it but android does
2. see above
3. any upload works indeed
4. Yep
5. it depends on what preview generators your have on the server
6. They are stored in the appdata. Removing them and rescanning can be done but is not recommended
