### ISSUE TITLE
Any chance to support excrypted files?

### ISSUE THREAD

**Issue by ahmedabt** [rullzer/previewgenerator#113]
It is very common use case to enable file encryption, any chance to support it?

**Comment by rullzer** [comment]
Not really.

This might all work fine with master key encryption.
But I won't write it (and will be unlikely to include it) as I don't use encryption myself (well I do but full disk encryption). As such I won't actively test it. I'd rather have it no supported than breaking all the time.

**Comment by ahmedabt** [comment]
It doesn't even work with master key encryption.

Anyway, I was expecting more positive feedback :-)

I am not sure why you are saying "and will be unlikely to include it" :-(

**Comment by rullzer** [comment]
I know it doesn't work with master key encryption. I just killed all encryption because some scenarios fail. And since I don't run with encryption I don't test it.

unless somebody volunteers to write the code with extensive tests I probably won't include it as it will just be more work for me and I maintain this app in my spare time.

**Comment by ahmedabt** [comment]
I just tried to disable the check for the encryption in the code to see what is gonna be the behavior and I can see that it works fine while the encryption is enabled and all the thumbnails were generated successfully.

What is the reason of this check? if the app already can work with the default encryption module.

Check:  if ($this->encryptionManager->isEnabled())

**Comment by rullzer** [comment]
It won't work with the default encryption module if you don't have master key encryption enabled.

The only reason it can work is if you upload a file via the webui and the big preview is already geneated then generating the smaller previews works.

But if you upload a file via webdav directly then the preview app has no way of decrypting your data. It also shouldn't or your encryption is useless.

I'll close this as I don't plan to implement it. Maybe at some point somebody will submit a PR.

**Comment by ahmedabt** [comment]
Enabling the master key is a very common use case, what about supporting this use case especially it doesn't require any big changes?

I can have a look on how to check if the master key is enabled or not and provide a patch.
