### ISSUE TITLE
store thumbnail cache outside s3 primary storage

### ISSUE THREAD

**Issue by najcardboyz** [rullzer/previewgenerator#115]
hi, i have installed nextcloud 13 with s3 as primary storage (multibucket)
so my app dir is in nextcloud-bucket-0
and user dir in nextcloud-bucket-1 and so on

i use preview generator, and it seems that thumbnail preview store in nextcloud-bucket-0, can i move dir of thumbnail outside on s3 bucket? change this to /var/www/nextcloud/thumbail for example

**Comment by rullzer** [comment]
The preview generator doesn't store anything it just requests previews from the system (which will be generated if they are not there).

Please submit this to https://github.com/nextcloud/server/issues
