### ISSUE TITLE
Reset square, width and heightSize settings

### ISSUE THREAD

**Issue by focus121** [rullzer/previewgenerator#136]
When I made some Settings like:
./occ config:app:set --value="32 64 1024" previewgenerator squareSize

How do I reset to default that all previews get generated?

**Comment by chichivica** [comment]
Just to make a pointer to your answer
```
./occ config:app:delete previewgenerator squareSizes
```
[from here ](https://help.nextcloud.com/t/reset-app-settings-previewgenerator/39377)
