### ISSUE TITLE
I can't find it in my app store?

### ISSUE THREAD

**Issue by jcklpe** [rullzer/previewgenerator#137]
I can see it on the website's app store but I can't see it when I look through the app store of my nextcloud installation?

**Comment by oscarcarlsson** [comment]
This is most likely unrelated to this plugin but a reflection of your own nextcloud setup. There are many variables at play here, so without any real information (version numbers of NC, setup used, if you can see any other plugins with their current versions that corresponds to the web app store versions) this is not a bug that can be used to fix anything, really.
