### ISSUE TITLE
preview:generate error

### ISSUE THREAD

**Issue by alfwro13** [rullzer/previewgenerator#14]
$ sudo -u oc_user php5 /www/owncloud/occ preview:generate

   **** Unrecoverable error in xref!
Error: /rangecheck in resolveR
Operand stack:
   --dict:3/3(L)--   --dict:4/4(L)--   --dict:4/4(L)--   --dict:4/4(L)--   4252440   1050   z▒▒▒
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--
 false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   1893   1   3   %oparray_pop   --nostringval--   --nostringval--   --nostringval--   --nostringval--   --nostringval--   --nostringval--   --nostringval--   --nostringval--   %array_continue   --nostringval--   --nostringval--   --nostringval--   %array_continue   --nostringval--   --nostringval--   --nostringval--   %array_continue   --nostringval--   --nostringval--   --nostring
val--   %array_continue   --nostringval--   --nostringval--   --nostringval--
Dictionary stack:
   --dict:1174/1684(ro)(G)--   --dict:1/20(G)--   --dict:82/200(L)--   --dict:82/200(L)--   --dict:109/127(ro)(G)--   --dict:293/300(ro)(G)--   --dict:21/31(
L)--   --dict:5/10(L)--
Current allocation mode is local
GPL Ghostscript 9.06: Unrecoverable error, exit code 1
Error: /typecheck in defineresource
Operand stack:
   --dict:10/19(L)--   false   DefaultGray   DeviceGray   ColorSpace   DefaultGray   DeviceGray
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--
 false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   1893   1   3   %oparray_pop   --nostringval--   --nostringval--   2
  1   1   --nostringval--   %for_pos_int_continue   --nostringval--   --nostringval--   --nostringval--   1862   5   7   %oparray_pop   defineresource   %errorexec_pop   --nostringval--
Dictionary stack:
   --dict:1175/1684(ro)(G)--   --dict:1/20(G)--   --dict:82/200(L)--   --dict:82/200(L)--   --dict:109/127(ro)(G)--   --dict:293/300(ro)(G)--   --dict:25/31(
L)--   --dict:16/20(ro)(G)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.06: Unrecoverable error, exit code 1
Error: /undefined in ▒d
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   1893   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:1174/1684(ro)(G)--   --dict:0/20(G)--   --dict:77/200(L)--
Current allocation mode is local
Current file position is 5
GPL Ghostscript 9.06: Unrecoverable error, exit code 1
PHP Fatal error:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0xb9 in /www/owncloud/lib/private/legacy/image.php on line 538

**Comment by oparoz** [comment]
You can safely ignore these errors. Imagemagick can't convert some of your files.
