### ISSUE TITLE
Can't regenerate preview folder after delete it.

### ISSUE THREAD

**Issue by castillo92** [rullzer/previewgenerator#140]
Hello, last week I deleted the folder where the previews was stored because some of them doesnt shows

Now I have this problem: This is the log when I execute "generqte-all"

> pi@RasPi_Server:~ $ sudo -u www-data php /var/www/nextcloud/occ preview:generate-all
> 2018-11-12T15:40:33+00:00 Scanning folder /User2/files
> 2018-11-12T15:40:33+00:00 Scanning folder /User2/files/Photos
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22641/82-100-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22633/86-100-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22637/100-67-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22643/87-100-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22635/55-100-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22631/100-100-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22636/100-67-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22630/75-100-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22639/93-100-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22652/100-75-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22645/100-75-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22647/100-100-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22648/100-66-max.jpg': No existe el fichero o el directorio
> stat: no se puede efectuar `stat' sobre '/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22655/100-56-max.jpg': No existe el fichero o el directorio

This is the log of NextCloud:

`

Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22915/97-100-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
-- | -- | --
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22915/97-100-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22915/97-100-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23004/75-100-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23004/75-100-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23004/75-100-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23003/75-100-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23003/75-100-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23003/75-100-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23007/75-100-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23007/75-100-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23007/75-100-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23005/75-100-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23005/75-100-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/23005/75-100-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22888/79-100-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22888/79-100-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22888/79-100-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22848/100-75-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22848/100-75-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22848/100-75-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22853/100-75-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22853/100-75-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22853/100-75-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22850/100-75-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22850/100-75-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22850/100-75-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22839/100-67-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22839/100-67-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22839/100-67-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 | 9 minutes ago
Error | filesize(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22831/100-75-max.jpg at /var/www/nextcloud/lib/private/LargeFileHelper.php#171 | 9 minutes ago
Error | stat(): stat failed for /mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22831/100-75-max.jpg at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142 | 9 minutes ago
Error | file_get_contents(/mnt/HDD1/NC_data/appdata_ocu75drfixe1/preview/22831/100-75-max.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216

`

NextCloud can't find the previews files, but I can't create it again. What can I do?

EDIT: I tried to purge the previews TABLE in Database with the command: but it doesn't solve the problem

> DROP TABLE oc_preview_generation;

EDIT2: Now pregenerqte doesnt work

> pi@RasPi_Server:~ $ sudo -u www-data php /var/www/nextcloud/occ preview:pre-generate
> 2018-11-12T16:11:49+00:00 
> 2018-11-12T16:11:49+00:00 In AbstractMySQLDriver.php line 53:
> 2018-11-12T16:11:49+00:00                                                                                                                
> 2018-11-12T16:11:49+00:00   An exception occurred while executing 'SELECT * FROM `oc_preview_generation` ORDER BY `id` ASC LIMIT 1000':  
> 2018-11-12T16:11:49+00:00                                                                                                                
> 2018-11-12T16:11:49+00:00   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloudDB.oc_preview_generation' doesn't exist  
> 2018-11-12T16:11:49+00:00                                                                                                                
> 2018-11-12T16:11:49+00:00 
> 2018-11-12T16:11:49+00:00 In PDOConnection.php line 106:
> 2018-11-12T16:11:49+00:00                                                                                                                
> 2018-11-12T16:11:49+00:00   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloudDB.oc_preview_generation' doesn't exist  
> 2018-11-12T16:11:49+00:00                                                                                                                
> 2018-11-12T16:11:49+00:00 
> 2018-11-12T16:11:49+00:00 In PDOConnection.php line 104:
> 2018-11-12T16:11:49+00:00                                                                                                                
> 2018-11-12T16:11:49+00:00   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloudDB.oc_preview_generation' doesn't exist  
> 2018-11-12T16:11:49+00:00                                                                                                                
> 2018-11-12T16:11:49+00:00 
> 2018-11-12T16:11:49+00:00 preview:pre-generate
> 2018-11-12T16:11:49+00:00 
>

**Comment by beccon4** [comment]
I messed it up the same way: running occ preview:generate-all which failed misserably due to full hard disk rendering the whole Nextcloud unusable. So in a moment of despair I deleted all the preview files from the directory and hoped to be able to recreate some. I couldn't

Now I can only display images created afterwards. All others show an error message like "can't find preview - please move to the next image while the current one is beeing deleted. (fortunately this doesn't happen)

PS: Is there a way to exclude some folders from a "generate-all"?

**Comment by nariox** [comment]
Try running `occ files:scan-app-data` and see if it helps.
The problem is that the table that links the files to the previews still has the old previews.
To save some disk space, you can check the documentation to set the max resolution of your previews:
https://docs.nextcloud.com/server/12/admin_manual/configuration_files/previews_configuration.html

**Comment by jboschuk** [comment]
Any feedback from @castillo92 or @beccon4 if the suggested approach fixed the problem?

It would be nice to know, because I would like to exclude the previews from my backup, as they only serve performance purposes but are not crucial data. But if this means I restore a broken NC, that's no good.

**Comment by castillo92** [comment]
> Any feedback from @castillo92 or @beccon4 if the suggested approach fixed the problem?
> 
> It would be nice to know, because I would like to exclude the previews from my backup, as they only serve performance purposes but are not crucial data. But if this means I restore a broken NC, that's no good.

I disabled the previews generator and did a fresh install of NextCloud.
Now, when I enter to a folder, I have to wait a minutes to see the previewa, but I dont care. I prefer to wait than have a program who doesn't work properly

It needs more develop and be more responsive with the user

**Comment by jboschuk** [comment]
@castillo92 thanks for the feedback!

**Comment by RuudschMaHinda** [comment]
> Try running `occ files:scan-app-data` and see if it helps.
> The problem is that the table that links the files to the previews still has the old previews.

It actually helped! Before running any command on my instance I usually try to check what it is doing. Unfortunately this command is completely undocumented for very "thin" reasoning.
See: https://github.com/nextcloud/documentation/issues/919

**Comment by nariox** [comment]
My guess is that you shouldn't *need* to run this command (since they've
implemented some fixes on Nextcloud), so they don't want to document it and
make people believe this is a "fix all" command. Maybe there might be risks
involved? (Makes me think of `btrfsck --repair`)

What this command does is go through the appdata folder and compare it to
tables in the databases and erase all missing entries, but I'm not totally
familiar with it either. In theory this app should be the kind you "set and
forget", but I myself have broken it a few times as I like to "fix things
until they're broken. I'm glad it helped you though.

**Comment by rullzer** [comment]
Sorry for the slow responses. But I wrote and maintain this app in my free time.

You should never manually remove data from appdata. And if you do run `./occ files:scan-app-data` to get it back into sync.

This app has nothing to do with preview locations. All it does it loop and request previews that are entirely handled in the server part.
