### ISSUE TITLE
'2006 MySQL server has gone away' error

### ISSUE THREAD

**Issue by haysebeyse** [rullzer/previewgenerator#143]
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `fileid`, `storage`, `path`, `path_hash`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`, `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [1, "bb771707935cb95bdf8dcab8a7d20686"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
```

**Steps to reproduce**
On a browser, go to a folder that contains `.jpg` images. Some files would have thumbnails and some others would not.

**Environment**
Server Configuration

OS: Ubuntu 18.04
Web server: Apache2 2.4.29
Database: MySQL 5.7.24
PHP version: 7.2
Nextcloud version: 14.0.3

**Client Configuration**
Browser: Mozilla Firefox 63.0.3
Operating system: Windows 10

**Relevant Nextcloud config**
```
'memcache.local' => '\\OC\\Memcache\\Redis',
'filelocking.enabled' => 'true',
'memcache.locking' => '\\OC\\Memcache\\Redis',
'enable_previews' => true,
'preview_max_x' => 2048,
'preview_max_y' => 2048,
'preview_max_scale_factor' => 1,
'preview_max_filesize_image' => 20,
'session_lifetime' => 86400,
```

**Comment by derritter88** [comment]
Seems that your MySQL has lost connection.
Have you checked your your MySQL server logs for any errors?

**Comment by bisherbas** [comment]
No mysql errors.

**Comment by derritter88** [comment]
hmm I still do not think that this is an issue of previewgenerator. As the error message is being generated by Nextcloud itself.

Is your MySQL running on the same machine?

**Comment by bisherbas** [comment]
Right. This error started showing up fewer times ever since I set up a cron job to pre-generate images daily.

**Comment by haysebeyse** [comment]
Support no longer needed.
