### ISSUE TITLE
previews not removed when deleting files

### ISSUE THREAD

**Issue by danielb42** [rullzer/previewgenerator#148]
In the past (some NC 14.0.x days) the preview dirs (e.g. `..../appdata_<chars>/preview/<number>`) would disappear (after cron) when the original files were deleted from Nextcloud. I noticed this behaviour has stopped and has not come back yet even with the current versions of NC or previewgenerator. So, obsolete previews are accumulating which can put quite some disk usage on a system.

Cron is set up correctly and runs every 10 minutes (new previews are generated perfectly). I ran  `preview:delete_old, preview:generate-all and preview:pre-generate` several times in between, but cannot get obsolete previews to disappear..

any thoughts? thanks!

**Comment by stratoss** [comment]
I'm quite new using this app, and was about to ask the same thing.

Seems like only postWrite hook has been watched, and no actions are executed when postDelete is triggered.

**Comment by rullzer** [comment]
Please double check the files are not still in the trashbin. Only when they are removed from there will the previews be cleaned up by a nextcloud background job

**Comment by danielb42** [comment]
Just double checked with new pictures (to make sure it's not a side effect of the trashbin problems of 14->15 upgrade). Sadly, still in the previews.

**Comment by rullzer** [comment]
Can you check if the cleanup job is still in your OC jobs fable. And check the last run time.

**Comment by danielb42** [comment]
Last run was 1400 UTC. So it seems my double-checking from the previous was not respected in any way, expected behaviour or not. I uploaded some new pics which sould be previewed at 1440 UTC and be deleted at 1500 UTC. Will report back then.

If it turns out cleanup runs only hourly this might explain the issue because I might never have investigated across hours. (And might have kept everything in trashbin on top of that.) So see you in a minute..

**Comment by danielb42** [comment]
Generation worked at 1440 UTC but `OC\Preview\BackgroundCleanupJob` did not run at 1500 UTC (last run still 1400 UTC). How/when is this thing triggered??
And am I even looking at the correct job?

**Comment by danielb42** [comment]
It ran just now: 1515 UTC. Obsolete previews are gone!

So for the original issue it's all good. But could you clarify on when exactly this job runs? Obviously it's not along with every cron execution. Also, I touched/removed another (textfile) exactly at 1515 UTC. Could _this_ have triggered the cleanup job in any way?

**Comment by rullzer** [comment]
So this is part of the Nextcloud server.
The job runs at most once an hour. However it depends on the number of other jobs etc when it exactly runs. However over the course of a day it should definitely run (at least if you have cron configured, if you have ajax cron it can take longer as it then only deletes 10 previews at a time to not time out).
