### ISSUE TITLE
oc_preview_generation is empty => Loading previews takes very long even though 20000 previews are generated

### ISSUE THREAD

**Issue by major-mayer** [rullzer/previewgenerator#149]
Sorry for the long title, I'm not used to write bug reports.
I installed the preview generator in december and it worked good for quite a while.
I generated all the previews with `generate-all` and after that i ran `pre-generate` once a day as a cron job.
The last week i wondered why loading the images takes sooo long although there are over 20000 previews in the appdata/preview folder waiting to get served.

When i try to view images (browser or app) the server load ramps up to 100 % as if it's creating all the images again, which shouldn't be nessecary.
I checked the network connections which file-id's are downloaded and guessed which will come next. 
`.../nextcloud/index.php/core/preview?fileId=82251&c=faaa4daecd7c35b62334065c86c32933&x=442&y=442&forceIcon=0`
Then I took the fileId and verified if those files are already in the preview folder and yes, all of them have been created in december.
Nevertheless it takes very long to watch the images/ previews because it's not using them.
I am also wondering why Nextcloud downloads alle the previews in the format (1024 * 1024) for small icons. 
Shouldn't it be enough to take the smaller ones?

Next i checked the database, especially the oc_preview_generation table, but it's completly empty.
I'm not into the project, but i guess there should be any entries at all, like in the other tables.

So my question now is, how can i resolve this problem preferably without recreating all the previews, which took really long on my NAS.
Thank you in advance.

Here are a few images to explain my problem
![grafik](https://user-images.githubusercontent.com/17907799/52356251-2e99ad00-2a34-11e9-916e-81ceadaee245.png)
![grafik](https://user-images.githubusercontent.com/17907799/52356435-7d474700-2a34-11e9-962c-aa782fda4e31.png)

**Comment by rullzer** [comment]
We switched the default preview sizes in NC15. There are now less but indeed also the 4k variant.

If you run `generate-all` it will just skip over the once that are already generated. But generate the once that are missing.

**Comment by rullzer** [comment]
Also the sizes are now powers of 4

64 256 1024 4096

**Comment by iGamerHD** [comment]
Thank you very much, ich changed the settings to "64 256 1024 4096" and it seems like `generate-all` works quite good and, as you said, only creates the missing previews.
I'm now a bit confused how the settings, that i can set in the occ cli ("./occ config:app:set --value=...") correspond with the preview-settings in the settings.php file?

Currently it's set to this:
`'enable_previews' => true,
'preview_max_x' => 1600,                                                                                               
'preview_max_y' => 1024,                                                                                              
'jpeg_quality' => 60,   `

However depending on which display i watch the photos in my browser, i get previews in the size of "4096*xxxx", "2048*xxxx" and "2560*xxxx" and so on... it's pretty random.
Those previews are not pre generated i guess, so is there a method to force the nextcloud client to only use the previews in the size that were pre-generated before?

**Comment by iGamerHD** [comment]
Also, when i use the previewgenerator the CPU load is very low ( about 20 %).
In contrast, when i try to view photos with now previews pre-generated, the load ramps up to about  95 %.
It would be great to use more CPU-Ressources for the previewgenerator too, so the generation is not that slow (it's taking several days on my system...)
