### ISSUE TITLE
unrecoverable error instead of error with notice

### ISSUE THREAD

**Issue by woolf76** [rullzer/previewgenerator#15]
Hello,
when I run:
/var/www/nextcloud# sudo -u www-data /usr/bin/php -f ./occ preview:"doesn't matter"
it goes thrue some image that generates error and script ends with log:
imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0x28 at /var/www/nextcloud/lib/private/legacy/image.php#538
"0x28" suggest problem with file but:
1. sometimes it's better to know :) ie which file is problematic.
2. it would be nice if preview will inform about corrupted jpeg and go straigt, but not die.
best regards
Krzysztof

**Comment by woolf76** [comment]
I did not implemented any encryption in nextcloud. It seems that better error handling do the job. I read on stackoverflow, some time ago, that commenting  some error catching code should workaround issue but I "think" :) that You have bigger experience...

**Comment by woolf76** [comment]
Earlier, when I didn't used preview, I saw sometimes unsupported marker 0x28 in the logs but previews was on it's place.
regards
Krzysztof

**Comment by rullzer** [comment]
This was a bug in core. Which was fixed with https://github.com/nextcloud/server/pull/3778 (it will be in NC12).
