### ISSUE TITLE
Different compression levels for smaller files

### ISSUE THREAD

**Issue by Gatak** [rullzer/previewgenerator#167]
It would be very useful to use higher compression levels for smaller files (thumbnails).

I also discovered that previewgenerator uses level 90, even though I have set 60 in the config. I recompressed with gimp and saw the comment that mentiones level 90. Perhaps the comment is wrong? In any case, the file size is halved when saved as level 60.

config.php
```
'preview_max_x' => '1920',
'preview_max_y' => '1200',
'jpeg_quality' => 60,
```

ls -l
```
-rw-r--r-- 1 apache nas 11795 Jun 30 11:18 256-256-crop.jpg
-rw-r--r-- 1 apache nas  5509 Jul  1 12:56 256-256-crop_recompressed.jpg
-rw-r--r-- 1 apache nas 32212 Jun 30 01:26 540-540-crop.jpg
-rw-r--r-- 1 apache nas 41106 Jun 30 01:26 960-540-max.jpg
```
![thumb](https://user-images.githubusercontent.com/1469150/60431509-44388a80-9c00-11e9-81fd-f431dc295a4e.png)
![gimp](https://user-images.githubusercontent.com/1469150/60431636-7cd86400-9c00-11e9-93dd-12f445dafbea.png)

**Comment by Gatak** [comment]
Just thinking of it. I think that it is NC and not previewgenerator that generated these thumbs. Does the jpeg quality setting affect NC's internal thumbnail generation?

**Comment by jkingcis** [comment]
@Gatak Didn't know that jpeg quality was set at 90. Lowering that value to 60 even 40 would make the preview folder size 2/3 times smaller. Not sure if it's NC's or Preview Generator's but that default value of 90 might need to be changed.

**Comment by Gatak** [comment]
I checked things again. The config is as follows:
```
'preview_max_x' => '1920',
'preview_max_y' => '1200',
'jpeg_quality' => 60,
```
Then I did:

1) put maintenance mode on
2) remove appdata/preview/*
3) empty oc_filecache
4) disable maintenance mode
5) open website, files view and let Nextcloud generate the initial thumbnails. 
6) change to grid mode and gallery view and open some pictures
7) check the filesizes and metadata for the generated thumbnails.

Note that jpeg_quality is at `60`, however the thumbnails are still generated as level `90`. Filesize and metadata is as in my previous post.

I think that the **`jpeg_quality`** option only affects previewgenerator and not Nextcloud's internal generation.  If this is the case, does NC internally support changing jpeg quality level?

**Comment by Gatak** [comment]
OK, so I checked the source code https://github.com/nextcloud/server/blob/master/lib/private/legacy/image.php#L383

```
protected function getJpegQuality() {
		$quality = $this->config->getAppValue('preview', 'jpeg_quality', 90);
		if ($quality !== null) {
			$quality = min(100, max(10, (int) $quality));
		}
		return $quality;
	}
```
Here we can see that Nextcloud uses a different setting for JPEG quality. It is set in in the app "**preview**" and the correct way to change this quality setting is by issuing:
**`occ config:app:set preview jpeg_quality --value="60"`**

Now, when my thumbnails are generating they are much smaller. **`256-256-crop.jpg`** is  **`5666`** bytes instead of **`11795`** bytes

**Comment by haarp** [comment]
So NC's own preview uses the **app** setting `jpeg_quality`, while the preview generator uses the **config.php** `jpeg_quality`? Sounds like a bug in the preview generator to me. It should definitely be using the same setting as NC does, not duplciate the config.

**Comment by rullzer** [comment]
This app uses that. The preview generator just requests the previews from Nextcloud. No generation at all it done here.

**Comment by Gatak** [comment]
> This app uses that. The preview generator just requests the previews from Nextcloud. No generation at all it done here.

This is not my findings in the previous post. Did you check that? 

Also in NC 19 and the new photos app things seem different again.

**Comment by rullzer** [comment]
I didn't check. But i know this app does not set anything related to preview compression levels.
