### ISSUE TITLE
Dng files

### ISSUE THREAD

**Issue by Happyfeet01** [rullzer/previewgenerator#171]
Is it possible to generate Previews from dng files?

**Comment by Scubage** [comment]
Same question from here. I add "'OC\\Preview\\DNG'" to config/config.php, but it do not work.

**Comment by rullzer** [comment]
This app just requests the previews. You need a preview provider avaialble in your server to be able to do that.

> Same question from here. I add "'OC\Preview\DNG'" to config/config.php, but it do not work.

Well that is not an available provider so it wouldn't be loaded.
