### ISSUE TITLE
Run in Docker?

### ISSUE THREAD

**Issue by hypervtechnics** [rullzer/previewgenerator#176]
Can this be added to the docker installation method somehow?

**Comment by spitzlei** [comment]
Do you use docker-compose?
Then simply add a cronjob at host, that executes the command inside the container:
`cd /$path-to-docker-compose.yml/ && docker-compose exec -T --user www-data app php occ preview:pre-generate`

Example: Running the job every night at 0:22 and the docker-compose.yml is in `/docker/nextcloud/` would result in this line in /etc/cron.d/nextcloud-previews
`0 22     * * *     root cd /docker/nextcloud/ && /usr/local/bin/docker-compose exec -T --user www-data app php occ preview:pre-generate`

**Comment by hypervtechnics** [comment]
How does it know in which container to run the command? Assuming that there is e.g. a redis or mariadb in the docker compose?

**Comment by spitzlei** [comment]
You just tell him :) You gave names to your containers in your docker-compose.yml. In my case its "app" for the nextcloud container. If you named your nextcloud container "nextcloud" the line would be: 
 `0 22 * * * root cd /docker/nextcloud/ && /usr/local/bin/docker-compose exec -T --user www-data nextcloud php occ preview:pre-generate`

**Comment by hypervtechnics** [comment]
Okay thank you very much. Would be cool to have this in the README :)
