### ISSUE TITLE
problems adding con job "pre-generate" with webcron

### ISSUE THREAD

**Issue by Skreboy** [rullzer/previewgenerator#18]
Hey,
maybe a stupid question, but how can I add

>  To enable pre-generation of previews you must add **./occ preview:pre-generate** to a system cron job

the generation of thumbnails, if I only can use the "Webcron" functionality of nextcloud. 

Thanks for any hint

**Comment by rullzer** [comment]
You can't use the webcron. The cron job might take way to much time for this to be done properly.
