### ISSUE TITLE
SVGs won't load in viewer when enabledPreviewProviders includes SVG

### ISSUE THREAD

**Issue by gorlilla** [rullzer/previewgenerator#183]
NextCloud v 17.0.3

Previewgenerator enabled and initial generation completed. 
config.php modified to include OC\Preview\SVG. 
Expected behavior: Thumbnails load for SVG, SVG loads in viewer when clicked. 
Actual Behavior: Thumbnails successfully load but the original SVG will **not** load in viewer when clicked. 

Previewgenerator enabled and initial generation completed. 
config.php does **not** include OC\Preview\SVG
Anticipated/Actual Behavior: Thumbnails do not load for SVG files but SVG successfully loads in the viewer when clicked. 

Unable to find any errors in logs so far. When the SVG does **not** load, the server returns a 207 response code. When the SVG does load (OC\Preview\SVG not enabled), the server responds 200. 

I'm still digging into this when i have free-time, but any help would be appreciated.

**Comment by rullzer** [comment]
This is not aproblem of this app. But rather an issue in server.
