### ISSUE TITLE
Local external folder - thumbnails generate per each user?

### ISSUE THREAD

**Issue by profzelonka** [rullzer/previewgenerator#187]
I'm sharing a huge photo folder locally via external folder. On running previewgenerator, I noticed all of the photos in that folder were processed per each user who has access to it. 

Shouldn't the folder be processed on it's own and the user simply have access to the generated previews? Else I'm probably stuck with the same previews times the amount of users that have access to it..

Thank you!

**Comment by rullzer** [comment]
This is how previews are handled in the server code.

Basically it is because if each user has access to the external folder via their own credentials Nextcloud has no way to find out they are the same file. Because the same path could have different images for different users.
