### ISSUE TITLE
Preview Generator 2.3 not showing up in NC Apps

### ISSUE THREAD

**Issue by feutl** [rullzer/previewgenerator#188]
Hi,
I am running NC 18.0.3 but I do not get the update for the Preview Generator App to Version 2.3 (usig 2.2 right now) which should be available based on https://apps.nextcloud.com/apps/previewgenerator

All other apps do update fine, is there a reason for this.

Thanks

**Comment by feutl** [comment]
Any help on this, I am still having 2.2 installed, no update shows up and the app disables itself automatically after a while.

**Comment by rullzer** [comment]
Seems like you then don't get the appstore responsed for some reason.
You can always manually replace the files with https://github.com/rullzer/previewgenerator/releases/download/v2.3.0/previewgenerator.tar.gz
