### ISSUE TITLE
Preview Generator 1.0.1 → Filename truncated in nextcloud.log

### ISSUE THREAD

**Issue by Sanookmakmak** [rullzer/previewgenerator#19]
NC 11.0.1 on  Ubuntu 16.04.1

The `occ `command `preview:generate-all` truncates the filenames in nextcloud.log, therefore debugging is impossible at the moment.

### Example

`sudo -u www-data php occ preview:generate-all`

`tail -f nextcloud.log`

MP3->getThumbnail('**\\/files\\/Archiv\\/K...**', 2048, 2048, false, O

### Detailed info

https://help.nextcloud.com/t/preview-generate-all-not-working/8190/4

**Comment by xraMsamohT** [comment]
The path is truncated after 15 characters.

**Comment by rullzer** [comment]
This is the stacktrace from php. Nothing we can do there.

**Comment by Sanookmakmak** [comment]
> Nothing we can do there.

Can't you print the filename into a logfile?

**Comment by rullzer** [comment]
There is already a PR to output a bit more info. But once i haev some time again I'll look into this.
