### ISSUE TITLE
NC19: App creates permanent RuntimeException in Nextcloud Log

### ISSUE THREAD

**Issue by LordSimal** [rullzer/previewgenerator#197]
I just manually updated my NC 18 to 19 and checked the log.

I permanently get new messages with the following message:

`RuntimeException: App class OCA\PreviewGenerator\AppInfo\Application is not setup via query() but directly`

Found this related issues with the same error: https://github.com/nextcloud/maps/issues/384

And the proposed solution: https://github.com/nextcloud/calendar/pull/1958/files#diff-079bbe455bfa9aeaf363ae1bc6415ba0R25

**Comment by MichaIng** [comment]
Can be closed, there is no `app.php` anymore, but a somehow related issue: https://github.com/rullzer/previewgenerator/issues/204
It seems like something in app or database is still expecting `app.php`. Good idea to check other app repos for similar error reports.
