### ISSUE TITLE
Preview Generator does not process HEIC files

### ISSUE THREAD

**Issue by sdalmeida** [rullzer/previewgenerator#199]
**Preview Generator version**: 2.3.0
**Nextcloud version**: 18.0.6

**Issue**:
Preview Generator skips HEIC images. It only seems to process `.jpg` and `.png` images.

**Expected Results:**
Preview images should be generated for HEIC formatted images too.

**Comment by rullzer** [comment]
You will need a preview provider for that. This app itself does not provide any previews.

**Comment by sdalmeida** [comment]
Hi @rullzer 
I'm not sure I understood your comment (sorry). The preview provider is already present in the NextCloud app, no? The issue is that HEIC images are being skipped, so If I want preview images for them, I need to manually select each item and create a preview from them (manually)

Is there something I'm missing?
Thank you for time.
