### ISSUE TITLE
Missing check about  running processes

### ISSUE THREAD

**Issue by blizzz** [rullzer/previewgenerator#2]
There is no lockfile, flag or other control that indicates that preview generation is still running. Thus,  when running ``./occ preview:pre-generate`` it  will just start to  do the same tasks. Depending on the activity on the instance, one run of ``./occ preview:pre-generate`` can already take a long time. So there is the chance that previews for each file are generated twice or multiple files (and making them processes run even longer).

**Comment by rullzer** [comment]
Ok so I finally also got bit by this. Thing is that if something goes wrong in the preview generation and php errors out (out of ram, gd error) a lockfile would not be ideal.

So what should solve it I think

1. When running the preGenerate just update the value after each file. Yes sure not awesome but when generating previews I really don't care about the extra query.
2. When done with the command clear the value
3. When a new command is launched. If the value is set but more than 30 minutes ago we assume it crashed.
