### ISSUE TITLE
Error while running preview:pre-generate

### ISSUE THREAD

**Issue by GAS85** [rullzer/previewgenerator#20]
Hi All,
 just after few seconds after I run
`sudo -u www-data php /var/www/nextcloud/occ preview:pre-generate`
I had an error:
`PHP Fatal error:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0xba in /var/www/nextcloud/lib/private/legacy/image.php on line 538`

My system is:
PHP 7.0.13
mysql 5.7.17
Nexcloud 11.0.1

**Comment by Sanookmakmak** [comment]
https://github.com/nextcloud/server/issues/3393

In my opinion the app should be downgraded to beta state.
Sorry.

**Comment by rullzer** [comment]
This was a server bug. That will be fixed in NC12 (https://github.com/nextcloud/server/pull/3778)
