### ISSUE TITLE
ImagickException: attempt to perform an operation not allowed by the security policy `PDF'

### ISSUE THREAD

**Issue by simphide** [rullzer/previewgenerator#200]
Hi,

I currently get the following error message in my NextCloud logs:

ImagickException: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408

Has anybody else this error?

**Comment by simphide** [comment]
nvm - was my fault

**Comment by Thovi98** [comment]
I have it too, how did you manage it ?

**Comment by simphide** [comment]
I can't remember - but I found it through googling

**Comment by Thovi98** [comment]
Yes thank you, I founded the solution but didn’t apply it well. Now I did it, thanks to this tutorial : https://cromwell-intl.com/open-source/pdf-not-authorized.html
Works fine now !
