### ISSUE TITLE
Syntax to change memory allowance?

### ISSUE THREAD

**Issue by y2klol** [rullzer/previewgenerator#208]
> I get "PHP Fatal error: Allowed memory size of X bytes exhausted"
> 
> You need to increase the memory allowance of PHP, by default it is 128 MB. You do that by changing the memory_limit in the php.ini file.
> 
> If you use the docker container you need to create the php.ini file in /usr/local/etc/php first.

I am using docker and I need to create the file myself. As someone who isn't familiar with coding, I am unsure as to what the syntax of increasing the limit looks like

`memory_limit = 12GB`

?

**Comment by v411e** [comment]
Have a look on https://github.com/nextcloud/docker/issues/1014#issuecomment-595887548
