### ISSUE TITLE
Skip failed file instead of cancelling the whole job

### ISSUE THREAD

**Issue by oparoz** [rullzer/previewgenerator#21]
I get this:
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 5742 bytes) in /lib/private/legacy/image.php on line 538
```
not a big deal if a thumbmnail can't be generated, but I think it just kills the whole job, which should be avoided.

**Comment by rullzer** [comment]
Well I have no way to catch PHP fatal errors.....

**Comment by oparoz** [comment]
Ah yes, that old chestnut... Let's close this then. It's the responsibility of the server to try and calculate the requirements to prevent the error from happening if it can.
Thanks!
