### ISSUE TITLE
Change Cache Directory

### ISSUE THREAD

**Issue by nicoselfhostedadventures** [rullzer/previewgenerator#225]
Hi,

Maybe this question was already answered, but I haven't found the answer yet: is it possible to change the folder for the generated previews? 

I store all my data on a mounted NFS drive which is mounted as the external storage in the Nextcloud, because of that I assigned only 32 GB to the Nextcloud my System which is not enough when I create image previews.

Is it possible to change the cache folder to the external storage e.g. my NFS mount? 

Thanks!

**Comment by poisonborz** [comment]
This is Nextcloud-specific, not PreviewGenerator. You need to change/move the "data" folder of your installation. This can be done through config.php, but search for the details and side effects.

**Comment by rullzer** [comment]
Exactly as @poisonborz says.
This app doesn't store the previews. We just request them. So that they are already there the next time. This is not something the app can do.
