### ISSUE TITLE
Preview Generator 1.0.1 → occ preview:pre-generate runs forever on certain PDF file

### ISSUE THREAD

**Issue by Sanookmakmak** [rullzer/previewgenerator#23]
No warnings in terminal, no messages in nextcloud.log or Apache log.

Example of PDF file and more info:

https://help.nextcloud.com/t/preview-generator-1-0-1-runs-forever-app-is-not-usable-anymore/8481

**Comment by Sanookmakmak** [comment]
I suspect this is a server issue as well as the [jpg too big issue](https://github.com/rullzer/previewgenerator/issues/25) @rullzer, isn't it?

**Comment by rullzer** [comment]
Yes this is the preview stuff in the server going rougue... please fill an issue in the server.
