### ISSUE TITLE
Preview Generator 1.0.1 → PDF file → occ preview:pre-generate does not display filename on warning

### ISSUE THREAD

**Issue by Sanookmakmak** [rullzer/previewgenerator#24]
Instead of displaying the filename it is displaying the producer → no way to debug :-(

![auswahl_003](https://cloud.githubusercontent.com/assets/24833757/22641540/71f61786-ec57-11e6-8858-1aa9a02641ef.png)

Here the PDF file in question

https://mega.nz/#!9A0E2BYA!9OG26578lm03HqaBHvqE8xtUPHWmwlWTAHeSfkizLfA

**Comment by rullzer** [comment]
This has to be fixed in the server as well.
