### ISSUE TITLE
Preview Generator 1.0.1 → big JPG file → occ preview:pre-generate → killed

### ISSUE THREAD

**Issue by Sanookmakmak** [rullzer/previewgenerator#25]
`sudo -u www-data php occ preview:pre-generate`
↓
`Getötet`

That's all what the app displays. No log in nextcloud.log or Apache as well. Just "killed".

It comes from a big jpg file which is created by Hugin panorama editor.

The preview generator app should parse the image size before processing it and ignore the preview generation if the image is too big.

How are the limitations at the moment and how can i adjust them?

**Comment by rullzer** [comment]
The app just requests previews from the system. It doesn't generate anything at all. Thus we also have no way of knowing what is to big. What will fail on your system etc. 

This fails in the server part of nextcloud so it is out of the apps scope.

**Comment by Sanookmakmak** [comment]
> have no way of knowing what is to big

That means for me that the app is not working.
Sorry.
