### ISSUE TITLE
I am afraid of running out of inodes

### ISSUE THREAD

**Issue by Sanookmakmak** [rullzer/previewgenerator#26]
The preview pictures are located in ~/nextcloud_data/appdata_XXXXXXX/preview
Each file has his own subfolder for the preview pictures in there.

The count of subfolders in a folder is limited by the inodes of the system. So if you have really lots of files, the chance to run out of inodes is growing. The result would be that you can't `ls -al` anymore in the preview folder.

I would suggest that the subfolders for the preview pictures are not stored in one huge folder, rather divided into a certain count of subfolders which contains subfolders as well.

Similar like the cache system of Squid proxy.

```
squid -z
ls -al /var/spool/squid
```

**Comment by rullzer** [comment]
Inodes are a limit of the filesystem. Not of a directory. So unless you have specific folders of appdata mapped to a different drive you will hit the limit anyway.
