### ISSUE TITLE
PHP Fatal error on generation

### ISSUE THREAD

**Issue by botweb** [rullzer/previewgenerator#27]
I'm recieving this error while generating a preview of an Android panorama image.

> PHP Fatal error:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0x93 in /home/cloud/public_html/lib/private/legacy/image.php on line 538

I don't need to support this file types, but it would be great, if the generator creation will not be aborted on any kind of error.

**Comment by rullzer** [comment]
The problem here is that we have no way to catch PHP fatal errors. So sadly not anything we can do in the app. Maybe in the nextcloud server we could do mimetype detection even smarter. but still going to be very hard I think.

**Comment by botweb** [comment]
Actually it's possible. It is needed to register an own error handler. After processing this could be reverted to the default handler.

http://stackoverflow.com/questions/277224/how-do-i-catch-a-php-fatal-error

**Comment by rullzer** [comment]
Ok let me phrase it differently. I'm not going to catch them in the app. Because all kind of stuff could go wrong that needs to be handled. Like memory. I/O errors. Errors in GD.
