### ISSUE TITLE
Nextcloud Box 'nextcloud.occ preview:pre-generate' ERROR

### ISSUE THREAD

**Issue by Seferi** [rullzer/previewgenerator#28]
I'm getting this error when i give the 'nextcloud.occ preview:pre-generate' command:

ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

**Comment by rullzer** [comment]
This seems like a misconfiguration of your enviroment. I have no way to fix this in the app. Maybe @oparoz can point you in the right direction?

**Comment by oparoz** [comment]
Correct, this is a problem related to the snap.
@Seferi I suggest you try to update you server environment and you snap and if the problem persists, please open an issue in nextcloud/nexctloud-snap

**Comment by rullzer** [comment]
Thnx @oparoz
