### ISSUE TITLE
Previews going to appdata folder and not being used

### ISSUE THREAD

**Issue by benqrn** [rullzer/previewgenerator#29]
Command runs fine and builds a large cache of previews in the appdata_xxxx/preview folder, but none of these files appear to be used by nextcloud, and the gallery app makes on-demand previews in the user/thumbnails folder instead of using the previews generated by this app.  Have I configured something incorrectly?

**Comment by mikedolx** [comment]
I can confirm that. I have the same behaviour. I ran the command via cron, and see the generated appdata folder, but as soon as i open the gallery the "on demand" generation of previews starts.

**Comment by benqrn** [comment]
I found this page - https://www.c-rieger.de/preview-generator-previews-jumping-up-as-popcorn/
even though it says to use the apps that are already installable through the owncloud app manager, I followed the instructions anyway and the gallery is now working as expected.

It seems that the current git master for Gallery 16.0.0 is NOT the same version of the Gallery app that is included with nextcloud's base install, despite having the exact same version.  Something is different and on-demand previews no longer use the userdir/thumbnails folder, they all are pulled or added to the appdata/preview folder.

I also had to clear any references to the appdata/preview folder in the file cache DB table because the nextcloud log was throwing errors about missing image previews (using occ to do a file cleanup did not help).

So I have it working now, but an explanation is required, what is different about the bundled Gallery app and the same app and app version from Git.

**Comment by rullzer** [comment]
Ah yes. This is a bug in gallery (which has been fixed).
Well git is different since it is the development branch.

**Comment by pieter-groeneweg** [comment]
Before you close. The fix is not yet in 16.0.0 as provided out of the box isn't it.
What fixed issue # in nextcloud/gallery are we talking about?

**Comment by benqrn** [comment]
Yes, it may be fixed in git but version 16.0.0 being bundled in Nextcloud and version 16.0.0 here are not the same, and Gallery in Nextcloud is not 'fixed'.

**Comment by rullzer** [comment]
It is fixed in gallery with https://github.com/nextcloud/gallery/pull/187

This app can't fix gallery so for this tracker it is fixed :wink:

**Comment by benqrn** [comment]
Is that issue with IPreview saying the fix won't be bundled by default until Nextcloud 12?  Just wondering if at some point the default install for Nextcloud 11 will be fixed.

**Comment by rullzer** [comment]
@benqrn well depends on @oparoz but my bet is on NC12. You could apply the patch from the PR yourself if you are up for it.

**Comment by benqrn** [comment]
Should I raise on issue on nextcloud/gallery that Gallery ver 16.0.0 in git and 16.0.0 bundled in NC 11 do not match?  That really is the issue I'm looking for to be solved, because if you install the previewgenerator plugin with a stock NC11 build, it will not work properly unless you go get 16.0.0 of Gallery from git.

**Comment by rullzer** [comment]
Feel free.

**Comment by pieter-groeneweg** [comment]
I am ready to learn some.. ;)

I have made the patches Now I am probably asking stupid things... but folder /user/thumbnails can be purged? as it now creates thumbs in /data/appdata_instanceid? Do I need to do anything else (in DB?)

**Comment by rullzer** [comment]
best is to run the `./occ preview:delete_old` command. As that will also remove them from the DB

**Comment by pieter-groeneweg** [comment]
awesome! Thanks!

Would be an good idea to add all these occ commands to the description in apps.nextcloud.com? (also for other apps using this feature).  Or did I miss a few paragraphs in the manual? This information is really useful. 
The more I discover each day, the more liking is turning into loving Nextcloud... :)

**Comment by benqrn** [comment]
the preview:delete_old command says (in the occ help) it does not work on NC11, I agree it doesn't seem to do anything.  I had to clean up the db file cache manually, and also remove the user/thumbnail folders manually.

**Comment by pieter-groeneweg** [comment]
@benqrn, odd, it worked fine for me. No errors all traces gone.

**Comment by AND51** [comment]
Hello,

Unfortunately, I would like to un-install previewgenerator, too. Like @benqrn said, the delete_old command did not produce any output, even with -v. However, I was able to detect severe activity with strace. I updated it to 1.0.3 an hour ago and tried it again.

What steps does delete_old do? The nextcloud/data/appdata_XXX/preview folder still contained plenty of previews. I delete everything inside this folder. The MySQL-table "oc_preview_genereation" is empty, I don't know how this was before. Moreover, I have no user/thumbnail directory which irritates me.

It would be nice if you can give me (and others) a short checklist for un-installing this app without leaving any orphaned files.

By the way, the created previews in appdata_XXX/preview had *.png extension, but imagemagick identified every picture as JPEG. Is this normal?

**Comment by rullzer** [comment]
@AND51 the just disable the previewgenerator app and then it is disabled. The app does not keep its own data. It just requests the previews from the server. So it is not this app that stores the previews in appdata_**/preview it is the server code. The server also stores the previews there that are generated on demand.

@benqrn it does not say that the command does not work on NC11. That command just cleansup all the old thumbnail folders. Since there were big issues with shared previews and all. Unfortutnaly the gallery app does not yet use it as we did not have time to update that.

@AND51 no they should not all be png... I'll look into that!

**Comment by oparoz** [comment]
> no they should not all be png... I'll look into that!

Actually, this is how it's been implemented in the Preview class. I'm guessing so that it doesn't have to care about file extensions, but it's pretty odd.

**Comment by rullzer** [comment]
@oparoz yes actually this has been it for a long time I think. But it is still odd. I mean it doesn't matter when we stream it since it is never accessed directly. But still odd ;)
