### ISSUE TITLE
README

### ISSUE THREAD

**Issue by strugee** [rullzer/previewgenerator#35]
This repo could use a README :)

**Comment by AND51** [comment]
I agree. I used the Preview Generator. However, I decided to un-install this app until there is a good knowledge base/documentation. Without solid backgrund information (how exactly it works, how to tune it, tipps&tricks, how to verify this plugin works, FAQ, how to solve problems, etc.) I have a bad feeling running such a "mysterious" app. The app description itself is quite short.

Don't get me wrong – I like this app and its principle. I also understand that the author develops it in his free time. I'm looking forward to enable this app again sooner or later.

**Comment by rullzer** [comment]
There will be a (short) README in 1.0.6
