### ISSUE TITLE
Link to app store in repo website

### ISSUE THREAD

**Issue by strugee** [rullzer/previewgenerator#37]
This repository's website (as seen on the default GitHub view) should probably link to https://apps.nextcloud.com/apps/previewgenerator.

**Comment by rullzer** [comment]
There is a link now. Improvements to the README.md are welcome.

**Comment by strugee** [comment]
@rullzer no, I meant, at the very top of the GitHub view, next to the repository's description.

Thanks so much for your work on this app <3

**Comment by rullzer** [comment]
Aaaah see I didn't even know there was a field for that. Fixed.

**Comment by strugee** [comment]
:tada: sweet!
