### ISSUE TITLE
mp3 file (attached) that triggers an exception during pre-generate

### ISSUE THREAD

**Issue by otubach** [rullzer/previewgenerator#44]
Hello,
I manually ran "generate all", then I manually ran pre-generate, and I got the following exception:

```
php -f /var/www/nextcloud/occ preview:pre-generate
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/nextcloud/lib/private/Files/Filesystem.php:719
Stack trace:
#0 /var/www/nextcloud/lib/private/legacy/image.php(597): OC\Files\Filesystem::file_get_contents('/var/www/nextcl...')
#1 /var/www/nextcloud/lib/private/Preview/MP3.php(80): OC_Image->loadFromFile('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/private/Preview/MP3.php(64): OC\Preview\MP3->getNoCoverThumbnail()
#3 /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php(54): OC\Preview\MP3->getThumbnail('/files/Document...', 2048, 2048, false, Object(OC\Files\View))

```

I'm running Nextcloud 11.0.2 (stable), with defaults apps and previewgenerator activated. previewgenerator 1.0.3.

After debugging a while, I found the file that triggers the exception, it's a mp3 file from a chinese book I bought, here it is:

[6440_p105_Bon.zip](https://github.com/rullzer/previewgenerator/files/852276/6440_p105_Bon.zip)

Thanks for the great pluging !

**Comment by otubach** [comment]
As a workaround, I disabled the preview generation for MP3s in my config/setup.php file : 

```
'enabledPreviewProviders' => array(
        'OC\Preview\PNG',
        'OC\Preview\JPEG',
        'OC\Preview\GIF',
        'OC\Preview\BMP',
        'OC\Preview\XBitmap',
        /* 'OC\Preview\MP3', */
        'OC\Preview\TXT',
        'OC\Preview\MarkDown'
),
```

Hope this helps,
Olivier

**Comment by rullzer** [comment]
This is fixed in the server master with https://github.com/nextcloud/server/pull/3794
Will be in NC12
