### ISSUE TITLE
Question about how the app works

### ISSUE THREAD

**Issue by alfwro13** [rullzer/previewgenerator#48]
Hi, I love the concept of this app but I'm bit confused how this app works.
I have created a test user (username: photos.db), uploaded 800MB folder full of photos.
then initiate the scan:

sudo -u www php /www/nextcloud/occ preview:generate-all photos.db

When that finished the appdata/preview folder was 500MB in size - that's nearly as big as the original folder. Furthermore when I login to nextcloud and switch to galery view I cannot see any speed improvment in the preview generation.

Am I missing something here?

**Comment by rullzer** [comment]
* We generate a shitload of previews ;) So that they are available once requested
* The current gallery is not yet suitable for this. Will be with the next release.

**Comment by rullzer** [comment]
Please try the Nextcloud 12 beta
