### ISSUE TITLE
php fatal error

### ISSUE THREAD

**Issue by yennor** [rullzer/previewgenerator#49]
I'm not 100% sure, but I think that error started appearing after the last update of the plugin. The version I'm using is: 1.0.5
I've got a cronjub which runs:
/var/www/html/cloud/occ preview:pre-generate

it then generates following error message.

PHP Fatal error:  Call to a member function file_get_contents() on null in /var/www/html/cloud/lib/private/Files/Filesystem.php on line 719

The last few months it was running well. But as I'm said, it happened shortly after the last update, but I can't say right now if directly, or if maybe some files were uploaded which generate that error.

**Comment by mikedolx** [comment]
Same here. 

I am running the preview generator app Version 1.0.5 with Nextcloud 11.0.2 (stable) within a Docker.

The command i am using is:
`docker exec -i mycontainername occ preview:pre-generate`

Any ideas, what i might be doing wrong?


here is the log output:

`An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /nextcloud/lib/private/Files/Filesystem.php:719
Stack trace:
#0 /nextcloud/lib/private/legacy/image.php(597): OC\Files\Filesystem::file_get_contents('/nextcloud/core...')
#1 /nextcloud/lib/private/Preview/MP3.php(80): OC_Image->loadFromFile('/nextcloud/core...')
#2 /nextcloud/lib/private/Preview/MP3.php(64): OC\Preview\MP3->getNoCoverThumbnail()
#3 /nextcloud/lib/private/Preview/GeneratorHelper.php(54): OC\Preview\MP3->getThumbnail('/files/NAS Musi...', 2048, 2048, false, Object(OC\Files\View))
#4 /nextcloud/lib/private/Preview/Generator.php(155): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\MP3), Object(OC\Files\Node\File), 2048, 2048)
#5 /nextcloud/lib/private/Preview/Generator.php(108): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'audio/mpeg')
#6 /nextcloud/lib/private/PreviewManager.php(182): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'audio/mpeg')
#7 /apps2/previewgenerator/lib/Command/PreGenerate.php(213): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#8 /apps2/previewgenerator/lib/Command/PreGenerate.php(199): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#9 /apps2/previewgenerator/lib/Command/PreGenerate.php(170): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#10 /apps2/previewgenerator/lib/Command/PreGenerate.php(137): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#11 /nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /nextcloud/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /nextcloud/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /nextcloud/console.php(90): OC\Console\Application->run()
#17 /nextcloud/occ(11): require_once('/nextcloud/cons...')
#18 {main}`

**Comment by Schroeffu** [comment]
Same issue here, similar stacktrace. 
Nextcloud 12.0.0 + 1.0.6 Preview Generator

`webuser@server:~site2$ /opt/plesk/php/7.1/bin/php occ preview:pre-generate
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/vhosts/sites/site2/lib/private/Files/Filesystem.php:717
Stack trace:
#0 /var/www/vhosts/sites/site2/lib/private/legacy/image.php(628): OC\Files\Filesystem::file_get_contents('/var/www/vhosts...')
#1 /var/www/vhosts/sites/site2/lib/private/Preview/Image.php(57): OC_Image->loadFromFile('/var/www/vhosts...')
#2 /var/www/vhosts/sites/site2/lib/private/Preview/GeneratorHelper.php(54): OC\Preview\Image->getThumbnail('/files/Foto/Fot...', 100, 100, false, Object(OC\Files\View))
#3 /var/www/vhosts/sites/site2/lib/private/Preview/Generator.php(162): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\JPEG), Object(OC\Files\Node\File), 100, 100)
#4 /var/www/vhosts/sites/site2/lib/private/Preview/Generator.php(110): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/jpeg')
#5 /var/www/vhosts/sites/site2/lib/private/PreviewManager.php(201): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'image/jpeg')
#6 /var/www/vhosts/sites/site2/apps/previewgenerator/lib/Command/PreGenerate.php(213): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#7 /var/www/vhosts/sites/site2/apps/previewgenerator/lib/Command/PreGenerate.php(245): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#8 /var/www/vhosts/sites/site2/apps/previewgenerator/lib/Command/PreGenerate.php(247): OCA\PreviewGenerator\Command\PreGenerate->processFolder(Object(OC\Files\Node\Folder))
#9 /var/www/vhosts/sites/site2/apps/previewgenerator/lib/Command/PreGenerate.php(201): OCA\PreviewGenerator\Command\PreGenerate->processFolder(Object(OC\Files\Node\Folder))
#10 /var/www/vhosts/sites/site2/apps/previewgenerator/lib/Command/PreGenerate.php(170): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#11 /var/www/vhosts/sites/site2/apps/previewgenerator/lib/Command/PreGenerate.php(137): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#12 /var/www/vhosts/sites/site2/3rdparty/symfony/console/Command/Command.php(256): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/vhosts/sites/site2/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/vhosts/sites/site2/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/vhosts/sites/site2/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/vhosts/sites/site2/lib/private/Console/Application.php(170): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/vhosts/sites/site2/console.php(92): OC\Console\Application->run()
#18 /var/www/vhosts/sites/site2/occ(11): require_once('/var/www/vhosts...')
`

**Comment by rullzer** [comment]
This is an issue in the server. Please open an issue (with exmaple image that fails) in https://github.com/nextcloud/server
