### ISSUE TITLE
Remote (or offline) preview generations

### ISSUE THREAD

**Issue by Glandos** [rullzer/previewgenerator#5]
Don't get me wrong: I was waiting for this app for a long time, so many thanks for making it real!

It is now time to ask for more 😉 

In my use case, my server is a not-so-powerful Atom CPU that is not really able to generate a lot of previews at once in a reasonable time. However, I have my desktop that have full access to the source files (in my case, via NFS), so it can theoretically do the job in less time. Is this possible in the current design? Maybe the algorithm needs an access to the database?

**Comment by rullzer** [comment]
No this is not possible. Since then your instance would not know anything about the generated previews etc.

Making the NC preview system more modular is still on the todo (but to be honest so is a lot of stuff). But this is something that has to be solved on a different level.

**Comment by Glandos** [comment]
This can be done using Imaginary service on your *fast&furious* desktop computer, as mentioned in #312
