### ISSUE TITLE
Fatal error running preview generator

### ISSUE THREAD

**Issue by appdesign1987** [rullzer/previewgenerator#50]
When i execute the command: "occ preview:pre-generate" i am getting the follwoing error:

` imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Invalid JPEG file structure: two SOI markers in /lib/private/legacy/image.php on line 538`

Not sure what it means but i comes everytime when i run the preview generator and it seems that because of it no more previews are beeing generated.

**Comment by nikc0069** [comment]
I also get this error. Prevents continuation of the preview generation past the folder it gets stuck on. And the log doesn't provide the troublesome file.

**Comment by rullzer** [comment]
This is an issue in the server as this app can't easily catch php errors. Please report to https://github.com/nextcloud/server with an example image that fails.
