### ISSUE TITLE
Include external storage?

### ISSUE THREAD

**Issue by wwwindisch** [rullzer/previewgenerator#56]
According to the desciption

> Listen to events that a file has been writen or modified and store it in the database

an tests with my NextCloud installation it seems, that `preview:generate-all` does not include external storage. Is that right?

If so: It would be a nice feature for future versions, to generate previews for external storage content (e.g. with an additional trigger like `./occ preview:generate-all [include-external]`).
I've added my photo collection to my NextCloud (runnig on a Raspberry PI 3) via SMB...and the on-demand generation speed of the thumbnail pics is not really satisfying...

Thanks a lot in advance!

**Comment by sstickel** [comment]
Running Nextcloud on my openmediavault installation, all my data is included via external storage/local. This way nextcloud automagically detects new files which did not work when I tried doing this with symlinks into the user folders. (Okay this was a little bit older version of oc, did not try with nc yet. But I like the way external storage includes itself into the interface.)

This way it is unfortunately pretty unusable for me

**Comment by wwwindisch** [comment]
Thanks for your advice, @sstickel 
It's good to know that it works for external storage integrated as "local"...this could be a possible option, if nothing else works.

In my case, SMB ist just much more convenient for the following reason:
I want to provide the same storage via Nextcloud and via an ordinary SMB share. For this, integrating the SMB share (which exists anyway) into Nextcloud is just a very elegant solution: The SMB users are identical with the Nextcloud users, which simplifies login and permission issues a lot.
And here comes the problem:
If the storage is integrated as "local" (which is possible since it's on the same machine), Nextcloud writes the data as "www-data" with too restrictive permissions (I've found no way to change the default permissions, so far...). Hence, the SMB users can't access this data.

A (rather nasty) workaround would be to integrate the storage as "local" and run a cron job, which sets the permissions right. But this will break the nice feature of the Nexcloud credentials being used as SMB credentials as well...

Using libsmbclient-php together with some tweaks of the RaspberryPI has sped up the on-demand computation of previews noticeably... That's why I'll probably stick to that solution for the sake of the aforementioned advantages...

**Comment by sstickel** [comment]
Sorry, you got me wrong. Neither "smb" nor "local" do work with this plugin. I think this is a general problem as this plugin does not "see" external storage.

To make the last comment clearer:
My old installation was based on Owncloud 11/12. I first set it up using symlinks into the user directories of Owncloud. (The symlinks ended in an smb mount point of my nas which ran on another xen dom-u.) Problem here was that Owncloud did not check for external file changes at all and I had to use `occ files:rescan` to get changes into Owncloud. It was unusable this way as I made a lot of changes NOT using Owncloud. But then I discovered that external storage thingy which solved all problems, as it scans the storage "on access" via Owncloud (Web Iface or webdav).

Now I switched to a recent Nextcloud version installed on a new server which is openmediavault based and I did not even try the symlink approach as "external storage" implements very good into the interface and has this "local" feature. But unfortunately this plugin also doesn't work using the local feature.

Sorry to mislead you.

**Comment by wwwindisch** [comment]
Ahh, OK, I got it. Thanks for clarifying! I hadn't even thought of your approach...
But I see that my current solution is probably the least problematic one out of all possible imperfect solutions :-)

**Comment by LukeLR** [comment]
Isn't it possible to fix this issue? I get that the plugin doesn't see external storages, so far. But the on-demand preview generator does see external storages, and is able to generate previews (if enabled in external storage settings). So I can't imagine that there really is no way to implement this in previewgenerator? I want to serve a lot of pictures to others which I already have on another drive, and I don't want to copy them into the data folder, so I'm using a local external share.

**Comment by touste** [comment]
I second this request, I have a similar setup and am facing the same issue.

Thanks!

**Comment by rullzer** [comment]
The app just traverses the file tree. I'll see if I can reproduce the issue.

**Comment by rullzer** [comment]
I just tested this on NC 13 with SFTP external storage and it works just fine. Of course it can only generate images for files NC knows about. (if they show up in the webUI they should be found by the app).

**Comment by touste** [comment]
I recently updated to 12.0.4 and it's working now. Thanks!

**Comment by sstickel** [comment]
Can confirm. Scan currently runs and detects my "local" external storage directories.

Thanks for fixing

**Comment by rullzer** [comment]
I didn't fix anything. Must be fixed server side ;-)

Anyway glad it is working now.
