### ISSUE TITLE
only scan shared folders ones

### ISSUE THREAD

**Issue by mind22** [rullzer/previewgenerator#57]
I recognized that the generate-all command does not verify if its a shared folder. So it scanned all shared folders for every user again. Maybe when there is some time in the future, this could be a little speed up.

**Comment by rullzer** [comment]
It should only 'scan' them. The previews should be generated only once.
But I get that if you share one big Photo folder with all your relatives this can be a big thing especailly on not to powerful hardware.

**Comment by HFranz** [comment]
Is it necessary to scan it multiple times? Actually it should be enough to scan it once, or not?
