### ISSUE TITLE
Generate custom resolutions

### ISSUE THREAD

**Issue by Loki3000** [rullzer/previewgenerator#6]
It's to be good to generate previews with custom resolution.
It's maybe something like that
occ preview:generate-all 200x100
syntax it's only example - need to be tuned.

**Comment by Ramalama2** [comment]
@rullzer
Any news about the custom argument above? :-)

**Comment by Ramalama2** [comment]
@rullzer
Is this addon dead? 
I'm still waiting xD

Cheers

**Comment by rullzer** [comment]
Not dead. I just do this in my spare time. And spare time has been slim lately. Don't worry it is on the todo.

**Comment by Ramalama2** [comment]
Cool :-) Thank you very much rullzer:-) 
I've seen you merged some new stuff to gallery like shared previews (ipreview). 

However, thank you very much!

**Comment by rullzer** [comment]
So I'm still not really sure how to do this. For the generate all I get the cli argument. However for the pre-generate (which is more usefull IMO) this is not at all trivial.

Maybe just some commands to add sizes. (and delete them). So you can add all your fancy custom resolutions and it gets triggered.

I Hope to have time soonish to do this. But no promises.

**Comment by pieter-groeneweg** [comment]
in https://github.com/owncloud/core/issues/11685 there was already some debate.
I just wonder (please excuse me, I do wonder a lot :) ) 
The previews are created according to the configuration in config.php, am I correct?
On question I never had an answer to.. is it possible to use this to reduce the amount of thumb previews and the sizes?

preview_max_scale_factor' => 1,
preview_max_filesize_image' => .25,

(can I set to .25 to have 250k? or can I only use Integers?)

Next thing, preview_max_x and y could also be set to reduce the amount of previews? default is 2048, but the usual 1024 would do fine, certainly on mobile devices..

**Comment by Loki3000** [comment]
> So I'm still not really sure how to do this.

Maybe send config file as a parameter? It will be quite simple then tons of CLI parameters?

**Comment by rullzer** [comment]
Should be fixed with #41 
That basically makes custom resolutions obsolete. Since we just generate everything (so gallery is also covered).

**Comment by cowai** [comment]
It would be good to have an option to only generate sizes needed for the gallery app? I have about 300k images, and now I have about 3 million thumbnails after I have generated them all.

**Comment by rullzer** [comment]
@cowai well yes but the sizes for the gallery app can differ very much depending on your screen size, resolution, HiDPI support etc.
