### ISSUE TITLE
generate-all ignores global log level

### ISSUE THREAD

**Issue by AND51** [rullzer/previewgenerator#65]
Hello!

The "generate-all" command seems to ignore the global log level of Nextcloud.

### Steps to reproduce

```
root@red:htdocs/config# grep level config.php -H
config.php:  'loglevel' => 2,
```

* Today I've got "php occ preview:generate-all" running in a screen.
* At the same time I was sorting and moving tons of pictures around (but I was connected via Samba, so previewgenerator should not be triggered).
* I noticed some log entries in htdocs/data/nextcloud.log with log level INFO.
* I finished sorting my pics.
* There are still INFO-messages logged. See screenshot.

### Expected
* No logging into htdocs/data/nextcloud.log

### Actual
* Logging into logfile, despite loglevel set to 2 (2=warning, 1=info)

### Screenshots

INFO messages:
![image](https://cloud.githubusercontent.com/assets/26226303/26792723/a536860e-4a1b-11e7-9a3a-c299b7963c40.png)

Used previewgenerator-command:
![image](https://cloud.githubusercontent.com/assets/26226303/26792849/0dd86402-4a1c-11e7-8093-fb705e2bab5e.png)

* Since I'm not doing anything right now (except for the generator that is still running), I conclude that this must be the preview generator.
* I double checked this and I saw that IMG_2990 was logged around the very same time it was processed by the command. (The screenshots were taken at close but different times, so you cannot see that.)
* Only thing is that the logging app is "admin_audit". I hope that bug is right in this project. If not, I appreciate for help by directing me to the right way.

**Comment by rullzer** [comment]
Well the log is not wrong we are acessing the previews. However we don't control the loggin of the admin audit app. 

If you think the admin audit logs to verbose fill a bug at https://github.com/nextcloud/server/issues
