### ISSUE TITLE
Only generate sizes that is used in gallery and files app.

### ISSUE THREAD

**Issue by cowai** [rullzer/previewgenerator#68]
Hi,
It would be much needed to generate only the sizes that are really needed.
I checked a random image and it had 21 previews. No wonder there is over 6 million previews on my servers,  and my oc_filecache table is 3.2GB.

I browsed some random folders in the gallery app, and it looks like the gallery app only uses previews with heigths  like 256, 512 and 2048. The files app uses 32x32 for the smallest preview and the sidebar preview was 768x512. At least some of the 21 generated previews is not ever needed.

Any thoughts?

**Comment by tobiasKaminsky** [comment]
The android client also uses these generated thumbnails.
Depending on your screen size it can be 256x256 or 128x128 or something else.
So if only the known sizes of web ui would be generated an user will have to wait very long for the thumbnails on the android device.

**Comment by rullzer** [comment]
Also 'known' sizes is hard. If you have an HDPI screen you request other sizes. For now this app will just generate all sizes as I have no way of knowing what will be requested.
