### ISSUE TITLE
Use relative paths

### ISSUE THREAD

**Issue by bavay** [rullzer/previewgenerator#69]
I recently renamed my data directory from /data/owncloud to /data/nextcloud. This had the unfortunate consequence of making all the previously generated previews invalid and forcing me to re-generate them all (which is quite unpleasant since it takes days...). I guess that the paths are coded as full paths, therefore making such as data directory rename quite unpleasant. If paths were stored relative to the data directory root, then the previews would still be valid and lots of time would be saved...

**Comment by MichaIng** [comment]
Note: This is not an issue of the previewgenerator app ;).

How to successfully change your data directory without loosing previews, shares, tags, comments etc. you can read here: https://help.nextcloud.com/t/howto-change-move-data-directory-after-installation/17170

At least the adjustment of `oc_storages` database table "should" also cover previews. Give feedback if you actually did that and it didn't work. So I would need to adjust the howto and would agree, that previews should be rely the same way on it than other file related information in database, shares, tags and comments.

**Comment by rullzer** [comment]
Yep not an issue with the previewgenerator app. We just request the previews for new files from the server.
