### ISSUE TITLE
How to see if it works?

### ISSUE THREAD

**Issue by RogerSik** [rullzer/previewgenerator#7]
Hello,

how I can see if it works? When I do it manually (or with crontab) is there no output. 

Edit1:

I tried it now with 

    sudo -u www-data php -f /var/www/occ preview:pre-generate -vvv

still no output. I'm doing something wrong? I'm using Ubuntu 16.04 with PHP7 with Nextcloud 11.

Greetings
Roger

**Comment by Ramalama2** [comment]
There is no output atm,
Read other issues here to get more info. 

This addon is very new let rullzer some time :-)

**Comment by elpraga** [comment]
You could use this command `find data/ -cmin -1` on you data directory. 

It will show you which files have been created within last minute and it should give you an idea what's the script doing. 

I used it myself.

**Comment by nickvergessen** [comment]
👍 for more output on verbose
