### ISSUE TITLE
what happens for images on external storage shared by all users

### ISSUE THREAD

**Issue by imthenachoman** [rullzer/previewgenerator#70]
In my NC setup I have an external storage `/path/to/my/photos` setup for all users. When `previewgenerator` generates image caches, will it generate one for each user or will it only generate one cache and share it for all the users?

**Comment by rullzer** [comment]
That depends how it is mapped. If the shared storage is really shared to all users it should generate only 1 preview.

**Comment by imthenachoman** [comment]
What does "really shared to all users" mean? How should I set it up?

**Comment by rullzer** [comment]
If you configured it as a global shared storage it works. If you configured it per user it will generate previews for each user.

**Comment by imthenachoman** [comment]
Awesome. Thank you! Is there anyway to check? Where are the generated preview files stored so I can check?

**Comment by rullzer** [comment]
they are stored in <datadir>/appdata_<instanceid>/previews/<fileid>

**Comment by imthenachoman** [comment]
Awesome. Thank you!

**Comment by Gatak** [comment]
Just to double check. If I add an external storage in global settings, but choose only some users, will the previews be shared?

running generate-all seems to loop over all users.

**Comment by dschrempf** [comment]
I don't understand what `global shared storage` means either. I have enabled external storage in `Settings -> Administration -> External storage`. I have set the availability to some users only (not all of them). Does this still count as `Global shared storage`?
