### ISSUE TITLE
Command already running

### ISSUE THREAD

**Issue by yamlfd** [rullzer/previewgenerator#71]
I get this message from cron for about 2 days now... every 15 minutes... i'm getting fat if I eat more cockies... :) what is causing this and how can I fix it?

**Comment by rullzer** [comment]
Ah so the command is launched but can take a long time (especially if you upload a lot of images). So we check the last activity and if that is recent enough we run the command.

**Comment by yamlfd** [comment]
That is not the problem. After 2 days it must be completed. There is a bug that cause this job never to complete

**Comment by Seik** [comment]
@yamlfd with pre-generate or generate-all?

**Comment by rullzer** [comment]
I never ran into that.
Does the command show up in `ps aux` ?

**Comment by yamlfd** [comment]
`occ preview:pre-generate`

There was one more issue in queue about this bug that helped me fixing it. Cannot remember all today, but I truncated a table or two and than it completed after 1 hour.

**Comment by Seik** [comment]
Try this, update to the last version, clean your `oc_preview_generation` table with something like `DELETE * FROM oc_preview_generation`, run `occ preview:pre-generate` to ensure that all your files have a preview generated.

If you are running into the same problem I was running with the new version you should be ok. See #73 for more info.
