### ISSUE TITLE
Unsupported marker type (again)

### ISSUE THREAD

**Issue by mikedolx** [rullzer/previewgenerator#72]
Hi,

I know that this issue was reported already several times. I am using NC12, which is why i am confused why this error occures. I am running the command "occ preview:pre-generate" via cron job each hour, and the error shown below (in the issue-template) is returned on each cron job.

Somehow there seems to be a corrupted file that causes this issue. Is there any way i can track down the file?

Please find attached the issue template of my server instance.

Thanks,

Regards,

Michael

### Steps to reproduce
1. run the occ command "occ preview:pre-generate"

### Expected behaviour
The preview generator successfully completes

### Actual behaviour
The following error is returned:

Unsupported marker type 0x99
Unsupported marker type 0x62
Unsupported marker type 0xb5
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4229981576 bytes) in /nextcloud/lib/private/legacy/image.php on line 765

### General server configuration

**Operating system:** Linux b40e551743ba 3.10.102 #15152 SMP Thu Jul 13 04:19:29 CST 2017 x86_64

**Web server:** nginx/1.13.3 (fpm-fcgi)

**Database:** mysql 5.5.54

**PHP version:** 7.1.7
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - sqlite3
 - zlib
 - ctype
 - curl
 - dom
 - fileinfo
 - filter
 - gd
 - hash
 - iconv
 - json
 - mbstring
 - SPL
 - PDO
 - pdo_sqlite
 - bz2
 - posix
 - readline
 - Reflection
 - session
 - SimpleXML
 - standard
 - tokenizer
 - xml
 - xmlreader
 - xmlwriter
 - mysqlnd
 - cgi-fcgi
 - apcu
 - Phar
 - exif
 - ftp
 - gmp
 - intl
 - ldap
 - mcrypt
 - mysqli
 - pcntl
 - pdo_mysql
 - pdo_pgsql
 - pgsql
 - zip
 - redis
 - smbclient
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from 11

**Where did you install Nextcloud from:**  https://github.com/Wonderfall/dockerfiles/tree/master/nextcloud

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - announcementcenter: 3.1.0
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.1
 - encryption: 1.6.0
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_external: 1.3.0
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - gpxpod: 2.1.4
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ownbackup: 17.5.0
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.1
 - rainloop: 5.0.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - firstrunwizard
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "datadirectory": "\/data",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "redis": {
        "host": "redis",
        "port": 6379
    },
    "instanceid": "ocadc83b19e7",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        ***REMOVED SENSITIVE VALUE***
    ],
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "mail_from_address": "info",
    "logdateformat": "Y-m-d H:i:s",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "loglevel": 2,
    "theme": ""
}
```
</details>

### Logs

<details>
        <summary>Cron job log</summary>

```
Standard output/error:
Unsupported marker type 0x99
Unsupported marker type 0x62
Unsupported marker type 0xb5
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4229981576 bytes) in /nextcloud/lib/private/legacy/image.php on line 765
```
</details>

**Comment by rullzer** [comment]
Please report this (with maybe an example image) to https://github.com/nextcloud/server as it is the server that does the actual preview generation.
