### ISSUE TITLE
Error while running preview:generate-all

### ISSUE THREAD

**Issue by tetzlav** [rullzer/previewgenerator#8]
after few hours i get

`root@omv:/var/www/nextcloud#  sudo -uowncloud php ./occ preview:generate-all
PHP Fatal error:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0x6f in /var/www/nextcloud/lib/private/legacy/image.php on line 538`

nexcloud v11.0.0
previewgenerator v1.0.1
php v5.6.29

**Comment by Babene03** [comment]
i have this problem
`PHP Fatal error: imagecreatefrompng(): gd-png: fatal libpng error: IDAT: CRC error
in /var/www/nextcloud/lib/private/legacy/image.php on line 545`

nextcloud v11.0.1 (stable)
previewgenerator v1.0.1
php v7.0.15

**Comment by annando** [comment]
After some minutes I get:
````
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 6000 bytes) in /path/to/nextcloud/lib/private/legacy/image.php on line 538
````
Is this a preview or nextcloud issue?

**Comment by rullzer** [comment]
@annando nextcloud issue. You might want to up your php memory limit 128MB is not much ;)

**Comment by rullzer** [comment]
As for the issue this is a corrupt file. We have no way to catch php fatal erros unfortunatly.

However with https://github.com/rullzer/previewgenerator/pull/31 the problem should be less of an issue since in the next run the file will just be skipped.

**Comment by annando** [comment]
@rullzer I already increased memory to 256MB - but it still happens. (Not so much, but still it does) I can't increase the memory more since the whole device has only got 1 GB memory. Although the error is caused inside of nextcloud, the question is if the process has some issues concerning the memory consumption?

**Comment by rullzer** [comment]
The app just requests data from the nextcloud server part. Nothing really fancy memory wise going on in the app.

**Comment by rullzer** [comment]
The fatal error was a bug in core. The patch is in NC12. https://github.com/nextcloud/server/pull/3778 that should fix it.
