### ISSUE TITLE
Can't get Cron to run.

### ISSUE THREAD

**Issue by ArtyV** [rullzer/previewgenerator#81]
When I use this /bin/sh: 1: /location/of/nextcloud/occ Permission denied
When I use this /bin/sh: 1: ./occ: No such file or directory
 
I can run it manually via terminal if sudo /location/of/nextcloud/occ
What I am doing wrong?

**Comment by chase9** [comment]
I found that, by default, my occ didn't have the execute bit. you'll need to run `chmod +x occ` in order to make it executable.

**Comment by ArtyV** [comment]
Looks like it is working.
Won't know for sure till the Full Generate finishes,  been running for a few days now........
