### ISSUE TITLE
PHP Fatal error: /var/www/html/lib/private/legacy/image.php on line 477

### ISSUE THREAD

**Issue by bakkegaard** [rullzer/previewgenerator#82]
When I run this command `sudo -u www-data ./occ preview:generate-all`
I get the following error:
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in /var/www/html/lib/private/legacy/image.php on line 477
`

**Comment by ArnisR** [comment]
You should increase memory limit in php.ini file (it's location depends from system).  For typical 24MPix image 128 MB memory can be short.  I've got this error even with 512M and increase it to 1G.

**Comment by rullzer** [comment]
Yep increase your memory limit in php.ini as mentioned by @ArnisR
