### ISSUE TITLE
/bin/sh: 1: /var/www/vhosts/xxx.de/httpdocs/occ: Permission denied

### ISSUE THREAD

**Issue by MorgJeh** [rullzer/previewgenerator#83]
I installed the app and created a cron job with the user root: /var/www/vhosts/xxxx.de/httpdocs/occ preview: pre-generate

When I run, I get the error:
/ bin / sh: 1: /var/www/vhosts/xxxx.de/httpdocs/occ: Permission denied

what am I doing wrong here?

**Comment by rullzer** [comment]
I guess you don't have the execute bit set on occ.

you can try:

```php /var/www/vhosts/xxxx.de/httpdocs/occ preview: pre-generate```

**Comment by MorgJeh** [comment]
Hello

I had to adjust that even further, because the Plesk php 5.9 runs. For me it looks like this:

sudo -u username /opt/plesk/php/5.6/bin/php/var/www/vhosts/xxxx/httpdocs/occ preview: pre-generate

The execution was aborted with an error:
Allowed memory size of 134217728 bytes exhausted (tried to allocate 3024 bytes) in /var/www/vhosts/xxxx.com/httpdocs/lib/private/legacy/image.php on line 477

**Comment by rullzer** [comment]
Ah well that is just an out of memory error. Generating previews does consume a lot of memory so more than 128 mb is recommended.
