### ISSUE TITLE
preview:generate-all only generates for first user

### ISSUE THREAD

**Issue by mklemme1** [rullzer/previewgenerator#84]
Hallo,
I have an existing server that I currently move from Owncloud to Nextcloud.
It already holds a large photo collection.

I the readme I find
> preview:generate-all [user-id]
> Loop over all files and try to generate previews for them. If user-id is supplied just loop over the files for that user.

Apparently "preview:generate-all" without a user does not generate previews for all users of the system. In fact, it scans the alphabetically first user and then terminates.

I am using nextcloud 12.0.4 and Preview Generator 1.0.7

**Comment by rullzer** [comment]
It should get called for all seen users (so if the user has ever logged in it should be called)

**Comment by HanZ92** [comment]
Can confirm. I have 4 users:
fyn, Ka, maalik, schattenfenger

It only genereated for User "Ka". Don't know why. Had to specify the user.

**Comment by mklemme1** [comment]
When I tried some more times, it Finally worked. 
I now think this issue is just a special of #77
