### ISSUE TITLE
Double entries in preview_generator table

### ISSUE THREAD

**Issue by it25fg** [rullzer/previewgenerator#85]
Nextcloud 12.0.4 preview_generator 1.0.7, instance with ~1000 users, ~5000000 files

I have executed the SQL from #62 (https://github.com/rullzer/previewgenerator/issues/62#issuecomment-316038941) so the cron job won't process duplicates anymore.

But after an hour the check query again returns  some duplicates (same owner+fileid, different sequence number). So it seems something continues to insert file ids into the oc_preview_generation table even if they're already there.

Where should I look to track this down?

**Comment by rullzer** [comment]
Ah yes. This can happen still. I'll take a look at this soonish (tm).
