### ISSUE TITLE
Pre-generate issue

### ISSUE THREAD

**Issue by ezraholm50** [rullzer/previewgenerator#9]
Hey, thanks for this app!

When running any command I get this error:

```
root@cloud:~# sudo -u www-data php /var/www/nextcloud/occ preview:pre-generate

                                                                                                                      
  [OC\Encryption\Exceptions\DecryptionFailedException]                                                                
  Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.  
                                                                                                                      

preview:pre-generate

PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/nextcloud/lib/private/Files/Filesystem.php:806
Stack trace:
#0 /var/www/nextcloud/lib/private/Files/View.php(2018): OC\Files\Filesystem::normalizePath('/usr/files/Ph...')
#1 /var/www/nextcloud/lib/private/Files/View.php(1156): OC\Files\View->unlockFile('/files/Photos/M...', 1)
#2 [internal function]: OC\Files\View->OC\Files\{closure}()
#3 /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))
#4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close()
#5 {main}
  thrown in /var/www/nextcloud/lib/private/Files/Filesystem.php on line 806

```

Anything to do with decryption?

**Comment by adamlove86** [comment]
same deal with the snap version:

sudo nextcloud.occ preview:pre-generate
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php

                                                                                        
  [OC\Encryption\Exceptions\DecryptionFailedException]                                  
  Can not decrypt this file, probably this is a shared file. Please ask the file owner  
   to reshare the file with you.                                                        
                                                                                        

preview:pre-generate

**Comment by rullzer** [comment]
Fixed with https://github.com/rullzer/previewgenerator/pull/33.
So for now the app won't work with encryption enabled. This is just to tricky.
