### ISSUE TITLE
Already processed folder ignored even after preview deletion

### ISSUE THREAD

**Issue by jeasto** [rullzer/previewgenerator#96]
Hi, 
I just used the new size specification function, so I decided to empty the preview folder and relaunch the preview `generate-all` to save some space.
But when I launch it, it seems to ignore every folders which were already processed before I cleaned the folder. 
What can I do ? Is there some kind of a cache I can clean ? 
Thanks !

**Comment by jeasto** [comment]
I found the answer : I had to clean the table oc_filecache by deleting all records with path like "appdata_%/preview%".
I hope this post can help some more people than me :-)

**Comment by jo-me** [comment]
Almost 3 years later and no progress on image & preview handling... had to do the same in NC20.
