### ISSUE TITLE
File extension is png, file type is jpg -> possible performance issue

### ISSUE THREAD

**Issue by ltzoss** [rullzer/previewgenerator#97]
The preview files are created by "gd-jpeg" as jpeg images.
`\00;CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 90`
The file extension is .png.

I'm wondering if this mix-up might result in broken previews or in wasted performance due to fall back routines that are trying to open the preview as png, fail, and then read the file header again to chose the right decompression routine (jpg).

**Comment by rullzer** [comment]
This is (or rather was) a bug in the server. it is fixed in NC13.
