### ISSUE TITLE
Fatal error with a to big file ?

### ISSUE THREAD

**Issue by benasse** [rullzer/previewgenerator#98]
When I run `sudo -u www-data ./occ preview:pre-generate` I get a Fatal error : 
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /var/www/html/lib/private/legacy/image.php on line 886
```
Is it a bug or due to my php configuration ?

**Comment by rullzer** [comment]
Probably it tries to generate the preview for an image that is to big.

Please increase the memory size in php.ini the default of 128MB is a bit low.
